// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.callingserver.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Identifies a participant in Azure Communication services. A participant is, for example, a phone number or an Azure
 * communication user.
 */
@Fluent
public final class CommunicationIdentifier {
    /*
     * The full Id of the identifier.
     */
    @JsonProperty(value = "rawId")
    private String rawId;

    /*
     * The communication user.
     */
    @JsonProperty(value = "communicationUser")
    private CommunicationUserIdentifier communicationUser;

    /*
     * The phone number.
     */
    @JsonProperty(value = "phoneNumber")
    private PhoneNumberIdentifier phoneNumber;

    /*
     * The Microsoft Teams user.
     */
    @JsonProperty(value = "microsoftTeamsUser")
    private MicrosoftTeamsUserIdentifier microsoftTeamsUser;

    /**
     * Get the rawId property: The full Id of the identifier.
     *
     * @return the rawId value.
     */
    public String getRawId() {
        return this.rawId;
    }

    /**
     * Set the rawId property: The full Id of the identifier.
     *
     * @param rawId the rawId value to set.
     * @return the CommunicationIdentifier object itself.
     */
    public CommunicationIdentifier setRawId(String rawId) {
        this.rawId = rawId;
        return this;
    }

    /**
     * Get the communicationUser property: The communication user.
     *
     * @return the communicationUser value.
     */
    public CommunicationUserIdentifier getCommunicationUser() {
        return this.communicationUser;
    }

    /**
     * Set the communicationUser property: The communication user.
     *
     * @param communicationUser the communicationUser value to set.
     * @return the CommunicationIdentifier object itself.
     */
    public CommunicationIdentifier setCommunicationUser(CommunicationUserIdentifier communicationUser) {
        this.communicationUser = communicationUser;
        return this;
    }

    /**
     * Get the phoneNumber property: The phone number.
     *
     * @return the phoneNumber value.
     */
    public PhoneNumberIdentifier getPhoneNumber() {
        return this.phoneNumber;
    }

    /**
     * Set the phoneNumber property: The phone number.
     *
     * @param phoneNumber the phoneNumber value to set.
     * @return the CommunicationIdentifier object itself.
     */
    public CommunicationIdentifier setPhoneNumber(PhoneNumberIdentifier phoneNumber) {
        this.phoneNumber = phoneNumber;
        return this;
    }

    /**
     * Get the microsoftTeamsUser property: The Microsoft Teams user.
     *
     * @return the microsoftTeamsUser value.
     */
    public MicrosoftTeamsUserIdentifier getMicrosoftTeamsUser() {
        return this.microsoftTeamsUser;
    }

    /**
     * Set the microsoftTeamsUser property: The Microsoft Teams user.
     *
     * @param microsoftTeamsUser the microsoftTeamsUser value to set.
     * @return the CommunicationIdentifier object itself.
     */
    public CommunicationIdentifier setMicrosoftTeamsUser(MicrosoftTeamsUserIdentifier microsoftTeamsUser) {
        this.microsoftTeamsUser = microsoftTeamsUser;
        return this;
    }
}
