// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.callingserver.implementation.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for CommunicationCloudEnvironment. */
public final class CommunicationCloudEnvironment extends ExpandableStringEnum<CommunicationCloudEnvironment> {
    /** Static value public for CommunicationCloudEnvironment. */
    public static final CommunicationCloudEnvironment PUBLIC = fromString("public");

    /** Static value dod for CommunicationCloudEnvironment. */
    public static final CommunicationCloudEnvironment DOD = fromString("dod");

    /** Static value gcch for CommunicationCloudEnvironment. */
    public static final CommunicationCloudEnvironment GCCH = fromString("gcch");

    /**
     * Creates or finds a CommunicationCloudEnvironment from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding CommunicationCloudEnvironment.
     */
    @JsonCreator
    public static CommunicationCloudEnvironment fromString(String name) {
        return fromString(name, CommunicationCloudEnvironment.class);
    }

    /** @return known CommunicationCloudEnvironment values. */
    public static Collection<CommunicationCloudEnvironment> values() {
        return values(CommunicationCloudEnvironment.class);
    }
}
