// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.callingserver.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Options for DTMF tone recognition. */
@Fluent
public final class DtmfOptions {
    /*
     * Collects the number of digit in DTMF.
     */
    @JsonProperty(value = "collectTones")
    private CollectTones collectTones;

    /*
     * Dtmf tone producer participant
     */
    @JsonProperty(value = "dtfmToneProducer")
    private CommunicationIdentifier dtfmToneProducer;

    /**
     * Get the collectTones property: Collects the number of digit in DTMF.
     *
     * @return the collectTones value.
     */
    public CollectTones getCollectTones() {
        return this.collectTones;
    }

    /**
     * Set the collectTones property: Collects the number of digit in DTMF.
     *
     * @param collectTones the collectTones value to set.
     * @return the DtmfOptions object itself.
     */
    public DtmfOptions setCollectTones(CollectTones collectTones) {
        this.collectTones = collectTones;
        return this;
    }

    /**
     * Get the dtfmToneProducer property: Dtmf tone producer participant.
     *
     * @return the dtfmToneProducer value.
     */
    public CommunicationIdentifier getDtfmToneProducer() {
        return this.dtfmToneProducer;
    }

    /**
     * Set the dtfmToneProducer property: Dtmf tone producer participant.
     *
     * @param dtfmToneProducer the dtfmToneProducer value to set.
     * @return the DtmfOptions object itself.
     */
    public DtmfOptions setDtfmToneProducer(CommunicationIdentifier dtfmToneProducer) {
        this.dtfmToneProducer = dtfmToneProducer;
        return this;
    }
}
